# -*- coding: utf-8 -*-
"""Food_Vision

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NgZ3kJsrrnLvGZ79cgN-hiKfK7H_rkAk
"""

# =========================================================
# 1. IMPORTS
# =========================================================
import tensorflow as tf
import tensorflow_datasets as tfds
from tensorflow.keras import layers
from tensorflow.keras.applications.efficientnet import EfficientNetB0, preprocess_input

# Silence warnings
tf.get_logger().setLevel("ERROR")

# =========================================================
# 2. CONFIG
# =========================================================
IMG_SIZE = 224
BATCH_SIZE = 32
EPOCHS = 10
AUTOTUNE = tf.data.AUTOTUNE

# =========================================================
# 3. LOAD FOOD-101 DATASET
# =========================================================
(train_data, test_data), ds_info = tfds.load(
    "food101",
    split=["train", "validation"],
    shuffle_files=True,
    as_supervised=True,
    with_info=True
)

NUM_CLASSES = ds_info.features["label"].num_classes
CLASS_NAMES = ds_info.features["label"].names

print("Number of classes:", NUM_CLASSES)

# =========================================================
# 4. PREPROCESSING FUNCTION
# =========================================================
def format_image(image, label):
    image = tf.image.resize(image, (IMG_SIZE, IMG_SIZE))
    image = preprocess_input(image)  # 🔥 CRITICAL FOR EFFICIENTNET
    return image, label

# =========================================================
# 5. PREPARE DATA PIPELINE
# =========================================================
train_data = (
    train_data
    .map(format_image, num_parallel_calls=AUTOTUNE)
    .shuffle(1000)
    .batch(BATCH_SIZE)
    .prefetch(AUTOTUNE)
)

test_data = (
    test_data
    .map(format_image, num_parallel_calls=AUTOTUNE)
    .batch(BATCH_SIZE)
    .prefetch(AUTOTUNE)
)

# =========================================================
# 6. BUILD MODEL (FEATURE EXTRACTION)
# =========================================================
base_model = EfficientNetB0(
    include_top=False,
    weights="imagenet",
    input_shape=(IMG_SIZE, IMG_SIZE, 3)
)

base_model.trainable = False  # FEATURE EXTRACTION

inputs = layers.Input(shape=(IMG_SIZE, IMG_SIZE, 3))
x = base_model(inputs, training=False)
x = layers.GlobalAveragePooling2D()(x)
x = layers.BatchNormalization()(x)
outputs = layers.Dense(NUM_CLASSES, activation="softmax")(x)

model = tf.keras.Model(inputs, outputs)

# =========================================================
# 7. COMPILE
# =========================================================
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

model.summary()

# =========================================================
# 8. CALLBACKS
# =========================================================
early_stop = tf.keras.callbacks.EarlyStopping(
    monitor="val_loss",
    patience=3,
    restore_best_weights=True
)

checkpoint = tf.keras.callbacks.ModelCheckpoint(
    "food101_efficientnetb0.keras",
    monitor="val_accuracy",
    save_best_only=True
)

# =========================================================
# 9. TRAIN (FEATURE EXTRACTION)
# =========================================================
history = model.fit(
    train_data,
    epochs=EPOCHS,
    validation_data=test_data,
    callbacks=[early_stop, checkpoint]
)